# Generated by Django 4.1.2 on 2022-10-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='weight',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='cal_fac',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
